import { NETWORK_TICK_MS, REMOTE_INTERPOLATION_MS } from '../src/shared/protocol/Timing';
/** Server-clock RTT samples. Nonces are generated by the transport owner.
 * Minimum recent RTT avoids granting extra rewind for a transient stall.
 * A client can delay replies, so the hard four-tick history cap remains essential. */
export class LatencyBudget {
  private pending: { nonce: string; sent: number } | null = null;
  private samples: { rtt: number; at: number }[] = [];
  begin(nonce: string, now: number) { this.pending = { nonce, sent: now }; }
  complete(nonce: unknown, now: number) {
    if (!this.pending || nonce !== this.pending.nonce) return false;
    const rtt = now - this.pending.sent; this.pending = null;
    if (!Number.isFinite(rtt) || rtt < 0 || rtt > 2500) return false;
    this.samples.push({ rtt, at: now }); this.samples = this.samples.slice(-8);
    return true;
  }
  shotFrame(receivedFrame: number, now: number): number | undefined {
    this.samples = this.samples.filter(s => now - s.at <= 10000);
    if (!this.samples.length) return undefined;
    const rtt = Math.min(...this.samples.map(s => s.rtt));
    // Remote rendering adds one nominal 15Hz interpolation interval. Reserve
    // one tick for execution; older queued commands expire in HitboxHistory.
    const ticks = Math.min(3, Math.floor((rtt / 2 + REMOTE_INTERPOLATION_MS) / NETWORK_TICK_MS));
    return Math.max(0, receivedFrame - ticks);
  }
  metrics(now: number) {
    const samples = this.samples.filter(s => now - s.at <= 10000);
    const values = samples.map(s => s.rtt);
    return { samples: values.length, rttMs: values.at(-1) ?? null,
      minRttMs: values.length ? Math.min(...values) : null,
      jitterMs: values.length > 1 ? Math.max(...values) - Math.min(...values) : null };
  }
}
