import './styles.css';
import { startCampaign } from './campaign';
import { startOnline } from './online';
import { startOfflineGrowth } from './offlineGrowth';
import { installAudioUI } from './client/audio/AudioSettings';
const query = new URLSearchParams(location.search);
if (query.has('lab') || ['lab', 'original'].includes(query.get('rules') ?? '')) startOfflineGrowth(true);
else if (query.has('online')) startOnline();
else if (query.has('offline') && query.has('growth')) startOfflineGrowth();
else if (query.has('offline')) startCampaign();
else startOnline();
installAudioUI();
